#!/usr/bin/env bash
# Regenerate install-plugins.sh from current installed_plugins.json + known_marketplaces.json
# Called by PostToolUse hook after `claude plugin install` commands.

set -euo pipefail

CLAUDE_DIR="$HOME/.claude"
INSTALLED="$CLAUDE_DIR/plugins/installed_plugins.json"
MARKETPLACES="$CLAUDE_DIR/plugins/known_marketplaces.json"
OUTPUT="$CLAUDE_DIR/scripts/install-plugins.sh"

if [[ ! -f "$INSTALLED" || ! -f "$MARKETPLACES" ]]; then
  exit 0
fi

# Extract marketplace repos: { name: repo }
declare -A MKT_MAP
while IFS=$'\t' read -r name repo; do
  MKT_MAP["$name"]="$repo"
done < <(python3 -c "
import json, sys
with open('$MARKETPLACES') as f:
    data = json.load(f)
for name, info in data.items():
    repo = info.get('source', {}).get('repo', '')
    if repo:
        print(f'{name}\t{repo}')
")

# Extract installed plugins: plugin@marketplace
PLUGINS=()
while IFS= read -r line; do
  PLUGINS+=("$line")
done < <(python3 -c "
import json
with open('$INSTALLED') as f:
    data = json.load(f)
for key in data.get('plugins', {}):
    # key format: plugin_name@marketplace_name
    print(key)
")

# Generate install-plugins.sh
cat > "$OUTPUT" << 'HEADER'
#!/usr/bin/env bash
# Install all Claude Code plugins from marketplaces.
# Auto-generated by sync-plugins.sh — do not edit manually.
# Run on a fresh machine after cloning the ~/.claude repo.
# Usage: bash ~/.claude/scripts/install-plugins.sh

set -euo pipefail

HEADER

# Write marketplaces
echo '# Step 1: Add marketplaces' >> "$OUTPUT"
echo 'declare -A MARKETPLACES=(' >> "$OUTPUT"
for name in "${!MKT_MAP[@]}"; do
  echo "  [\"${MKT_MAP[$name]}\"]=\"$name\"" >> "$OUTPUT"
done
echo ')' >> "$OUTPUT"
echo '' >> "$OUTPUT"

# Write plugins
echo '# Step 2: Plugins to install' >> "$OUTPUT"
echo 'PLUGINS=(' >> "$OUTPUT"
for plugin in "${PLUGINS[@]}"; do
  echo "  \"$plugin\"" >> "$OUTPUT"
done
echo ')' >> "$OUTPUT"

cat >> "$OUTPUT" << 'FOOTER'

echo "=== Adding ${#MARKETPLACES[@]} marketplaces ==="
echo ""
for repo in "${!MARKETPLACES[@]}"; do
  name="${MARKETPLACES[$repo]}"
  echo "-> Adding marketplace: ${name} (${repo})"
  claude plugin marketplace add "${repo}" 2>&1 || echo "   (already added or failed)"
done

echo ""
echo "=== Installing ${#PLUGINS[@]} plugins ==="
echo ""
for plugin in "${PLUGINS[@]}"; do
  echo "-> Installing: ${plugin}"
  if claude plugin install "${plugin}" 2>&1; then
    echo "   OK"
  else
    echo "   FAILED: ${plugin} - try manually: claude plugin install ${plugin}"
  fi
  echo ""
done

echo ""
echo "=== Post-install ==="
echo "After ECC plugin is installed, run in a Claude Code session:"
echo '  /configure-ecc'
echo "This installs rules/ and agents/ from ECC."
echo ""
echo "Done. Run 'claude plugin list' to verify."
FOOTER

chmod +x "$OUTPUT"

# Auto-commit if in git repo
if cd "$CLAUDE_DIR" && git rev-parse --is-inside-work-tree &>/dev/null; then
  if ! git diff --quiet scripts/install-plugins.sh 2>/dev/null; then
    git add -f scripts/install-plugins.sh scripts/sync-plugins.sh
    git commit -m "chore: auto-sync install-plugins.sh" --no-verify 2>/dev/null || true
  fi
fi
